[package]
name = "simulation"
version = "0.1.0"
edition = "2024"

[features]
hotpath = [
    "hotpath/hotpath",
    "capture/hotpath",
    "client/hotpath",
]
hotpath-cpu = [
    "hotpath/hotpath-cpu",
    "capture/hotpath-cpu",
    "client/hotpath-cpu",
]
hotpath-alloc = [
    "hotpath/hotpath-alloc",
    "capture/hotpath-alloc",
    "client/hotpath-alloc",
]

[dependencies]
clap = { version = "4.6.5", features = ["derive"] }

log = { workspace = true }
env_logger = { workspace = true }

gpui = { workspace = true }
gpui-component = { workspace = true }
gpui_platform = { workspace = true }

client = { workspace = true }
server = { workspace = true }

capture = { workspace = true }

smol = { workspace = true }
tokio = { workspace = true }

rpc = { workspace = true }
hotpath = { workspace = true }
