[package]
name = "hazel_client"
version = "0.1.0"
edition = "2024"

[features]
profiling = ["tracy-client/enable"]

[dependencies]
rpc = { workspace = true }
capture = { workspace = true }
streaming_common = { workspace = true }
client_macros = { workspace = true }

gpui = { workspace = true }
gpui_platform = { workspace = true }
gpui-component = { workspace = true }

smol = { workspace = true }
tokio = { workspace = true }

anyhow = { workspace = true }
rmp-serde = { workspace = true }
sea-orm = { workspace = true }
bytes = { workspace = true }
atomic_float = { workspace = true }
crossbeam = { workspace = true }
ringbuf = { workspace = true }
tracy-client = { workspace = true }

rust-embed = "8.11.0"
unicode-segmentation = "1.12.0"
reed-solomon-simd = "3.1.0"

tracing = "0.1.44"
clap = { version = "4.5.60", features = ["derive"] }
atomic = { version = "0.6.1", default-features = false }
atomic_enum = "0.3.0"
drm-fourcc = "2.2.0"
