//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use rpc::{models::markers, tag_entity};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "message")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub content: Json,
    pub channel_id: i32,
    pub sent_by: i32,
    pub sent_at: DateTime,
}

tag_entity!(Model, markers::Message);

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
